import { translate, formatMessage } from "./locale";
// Display values shared by web and mobile. Keep platform-specific styling and navigation in the app.
const ENGLISH_TEXT = {
  hospitalFallback: "hospital",
  dateBadge: "DATE",
  bookingUnit: "booking",
  bookingsUnit: "bookings",
  selfSuffix: " (Self)",
  pluralSuffix: "s",
  stepUnit: "steps",
  calorieUnit: "kcal",
  mealUnit: "meal",
  meals: "meals",
  todayBadge: "TODAY",
  unknownBadge: "UNKNOWN",
  pendingBadge: "PENDING",
  ohoindiaCustomerApp2: "OHOINDIA CUSTOMER APP",
  expiresToday: "Expires today",
  expiryNotProvided: "Expiry not provided",
  notStarted: "Not started",
  accountDetails: "Account details",
  ohoindiaMembershipCard: "OHOINDIA membership card",
  showBackOfOhoindiaMembershipCard: "Show back of OHOINDIA membership card",
  ohoindiaPrivilegeFamilyCareHealthcareWellnessHappinessNotTransferable:
    "OHOINDIA Privilege Family Care. Healthcare, Wellness, Happiness. Not transferable.",
  membershipNumber: "Membership number",
  expired: "Expired",
  validityExpired: "Validity · Expired",
  validity: "Validity",
  notProvided: "Not provided",
  to: " to",
  ohoindiaCardBackConsultationsDiscountsDiagnosticsHealthCampsAnd:
    "OHOINDIA card back: consultations, discounts, diagnostics, health camps and insurance. Call or WhatsApp +91 7032 107 108 or +91 7671 997 108. Terms and conditions apply; insurance is provided by partners. This card is company property.",
  viewBenefits: "View Benefits",
  openParenthesis: " (",
  closeParenthesis: ")",
  bookNow: "Book Now",
  viewDetails: "View Details",
  homeIcon: "⌂",
  gridIcon: "▣",
  walletIcon: "▰",
  diamondIcon: "♢",
  circleIcon: "○",
  backArrow: "←",
  starIcon: "★",
  locationIcon: "⌖",
  chevronRight: "›",
  heartIcon: "♡",
  externalLinkIcon: "↗",
  settingsIcon: "⚙",
  ohoindia: "OHOINDIA",
  aHyperlocalHealthFintechForBharat: "A Hyperlocal Health Fintech for Bharat",
  home: "Home",
  bookings: "Bookings",
  wallet: "Wallet",
  notifications: "Notifications",
  profile: "Profile",
  searchDoctorsHospitalsTests: "Search doctors, hospitals, tests...",
  searchIcon: "⌕",
  microphoneIcon: "🎙️",
  quickActions: "Quick Actions",
  zeroCash: "Zero-Cash",
  opd: "OPD",
  scanPay: "Scan & Pay",
  qr: "QR",
  pharmacy: "Pharmacy",
  subsidies: "Subsidies",
  nameNotProvided: "Name not provided",
  familyMember: "Family member",
  coveredMember: "Covered member",
  accountDetails2: "Account Details",
  yourFamilyHealthAccount: "YOUR FAMILY HEALTH ACCOUNT",
  yourAccount: "Your account",
  membershipFamilyCoverageAndPackageValidityInOnePlace:
    "Membership, family coverage and package validity in one place.",
  loadingAccountDetails: "Loading account details...",
  someDetailsCouldNotBeLoaded: "Some details could not be loaded.",
  tryAgain: "Try again",
  accountHolder: "Account holder",
  fullName: "Full name",
  memberId: "Member ID",
  mobileNumber: "Mobile number",
  email: "Email",
  dateOfBirth: "Date of birth",
  age: "Age",
  gender: "Gender",
  group: "Group",
  address: "Address",
  kycVerification: "KYC verification",
  loading: "Loading...",
  unavailable: "Unavailable",
  verified: "Verified",
  incomplete: "Incomplete",
  addressVerification: "Address verification",
  membership: "Membership",
  status: "Status",
  cardNumber: "Card number",
  validFrom: "Valid from",
  validUntil: "Valid until",
  familyMembers: "Family members",
  accountHolderAndFamilyMembersListedInYourPackage:
    "Account holder and family members listed in your package policies.",
  selfAccountHolder: "Self · Account holder",
  mobile: "Mobile",
  packageCoverage: "Package coverage",
  package: "Package",
  validityStatus: "Validity status",
  issuedOn: "Issued on",
  loadingFamilyDetails: "Loading family details...",
  familyCoverageUnavailablePleaseTryAgainLater:
    "Family coverage unavailable. Please try again later.",
  noAdditionalFamilyMembersListedInYourPackageRecords:
    "No additional family members listed in your package records.",
  packagesValidity: "Packages & validity",
  explorePackages: "Explore packages",
  loadingPackages: "Loading packages...",
  packagesUnavailablePleaseTryAgainLater:
    "Packages unavailable. Please try again later.",
  noPurchasedPackages: "No purchased packages.",
  inactive: "Inactive",
  valid: "Valid",
  active: "Active",
  expiryStatus: "Expiry status",
  category: "Category",
  amountPaid: "Amount paid",
  sumAssured: "Sum assured",
  adultLimit: "Adult limit",
  childLimit: "Child limit",
  memberLimit: "Member limit",
  policy: "Policy",
  policyCoiNumber: "Policy / COI number: ",
  nominee: "Nominee: ",
  needHelpWithYourAccount: "Need help with your account?",
  call: "Call ",
  mobileNumberMustStartWith678Or:
    "Mobile number must start with 6, 7, 8, or 9.",
  errorVerifyingMobileNumberTryAgain:
    "Error verifying mobile number. Try again.",
  fullNameIsRequired: "Full Name is required.",
  unableToSendOtpPleaseTryAgain: "Unable to send OTP. Please try again.",
  pleaseEnterAValid10DigitMobileNumber:
    "Please enter a valid 10-digit mobile number.",
  pleaseEnterA4DigitPassword: "Please enter a 4-digit password.",
  loginFailedPleaseTryAgain: "Login failed. Please try again.",
  somethingWentWrongPleaseTryAgain: "Something went wrong. Please try again.",
  yourFamilySHealthAccount: "YOUR FAMILY'S HEALTH ACCOUNT",
  everydayCare: "Everyday care.",
  extraordinaryPeaceOfMind: "Extraordinary peace of mind.",
  manageYourFamilySRoutineHealthcareMembershipsAndAppointments:
    "Manage your family's routine healthcare, memberships, and appointments in one place.",
  value01: "01",
  yourCareConnected: "Your care, connected",
  findDoctorsAndHospitalsInYourNetwork:
    "Find doctors and hospitals in your network.",
  value02: "02",
  yourBenefitsTogether: "Your benefits, together",
  keepYourMembershipAndHealthPackagesClose:
    "Keep your membership and health packages close.",
  value03: "03",
  yourFamilyFirst: "Your family, first",
  manageAppointmentsAndFamilyHealthRecords:
    "Manage appointments and family health records.",
  discoverHowOhoindiaWorks: "Discover how OHOINDIA works ",
  memberAccess: "MEMBER ACCESS",
  joinTheOhoFamily: "Join the OHO family",
  welcomeToOhoindia: "Welcome to OHOINDIA",
  enterYourMobileNumberToSignInOrCreate:
    "Enter your mobile number to sign in or create an account.",
  enterMobileNumber: "Enter Mobile Number ",
  requiredMarker: "*",
  value91: "+91",
  enterMobileNumber2: "Enter Mobile Number",
  checkingMobileNumber: "Checking mobile number...",
  password: "Password",
  enter4DigitPassword: "Enter 4-digit Password",
  hidePassword: "Hide password",
  showPassword: "Show password",
  hide: "Hide",
  show: "Show",
  forgotYourPassword: "Forgot your password?",
  newCustomerPleaseCreateAnAccount: "New Customer – Please create an account.",
  fullNameAsPerAadhar: "Full Name (as per Aadhar)",
  enterFullNameAsPerAadhar: "Enter Full Name as per Aadhar",
  pleaseWait: "Please wait...",
  login: "Login",
  sendOtp: "Send OTP",
  continue: "Continue",
  yourAccountConnectsYouToYourFamilySCare:
    "Your account connects you to your family's care.",
  hospitalServiceAreas: "Hospital service areas",
  ourNetworkPartneredHospitalServicesAreAvailableIn:
    "OUR NETWORK-PARTNERED HOSPITAL SERVICES ARE AVAILABLE IN :",
  hyderabadRangareddyMedchalMalkajgiriSangareddyKhammamWarangalSiddipetAnd:
    "Hyderabad, Rangareddy, Medchal–Malkajgiri, Sangareddy, Khammam, Warangal, Siddipet, and Medak",
  allRightsReservedOhoindia: "All rights reserved. © OHOINDIA",
  poweredByOhoindiaTechnologyV10: "Powered by OHOINDIA TECHNOLOGY v1.0",
  privacyPolicy: "Privacy Policy",
  unableToResendOtp: "Unable to resend OTP.",
  pleaseEnterTheComplete6DigitOtp: "Please enter the complete 6-digit OTP.",
  enterA4DigitPasswordAndMatchingConfirmation:
    "Enter a 4-digit password and matching confirmation.",
  otpVerificationFailed: "OTP verification failed.",
  unableToUpdatePassword: "Unable to update password.",
  primary: "Primary",
  customerCreationFailedPleaseTryAgain:
    "Customer creation failed. Please try again.",
  backToLogin: "Back to login",
  setNewPassword: "Set New Password",
  verifyOtp: "Verify OTP",
  yourMobileNumberHasBeenVerified: "Your mobile number has been verified.",
  new4DigitPassword: "New 4-digit password",
  confirmPassword: "Confirm password",
  otp: "OTP",
  maximumResendLimitReached: "Maximum resend limit reached",
  resendOtp: "Resend OTP",
  savePassword: "Save Password",
  createAccount: "Create Account",
  verifyContinue: "Verify & Continue",
  loginDidNotReturnAValidSessionPleaseTry:
    "Login did not return a valid session. Please try again.",
  yourHealth: "Your Health.",
  ourPriority: "Our Priority.",
  familyIcon: "👨‍👩‍👧",
  shieldIcon: "🛡️",
  tapAnywhereToContinue: "Tap anywhere to continue",
  welcomeBack: "Welcome Back!",
  pleaseLoginToContinue: "Please login to continue",
  phoneIcon: "☎",
  or: "or",
  continueWithGoogle: "🌈 Continue with Google",
  continueWithApple: "● Continue with Apple",
  newToOho: "New to OHO? ",
  signUp: "Sign Up",
  weHaveSentA6DigitOtpTo: "We have sent a 6 digit OTP to",
  value919876543210: "+91 98765 43210",
  resendOtpIn: "Resend OTP in ",
  value0025: "00:25",
  backspaceIcon: "⌫",
  bookAppointment: "Book Appointment",
  selectDate: "Select Date",
  mon: "Mon",
  tue: "Tue",
  wed: "Wed",
  thu: "Thu",
  fri: "Fri",
  may: "May",
  selectTime: "Select Time",
  value0900Am: "09:00 AM",
  value0930Am: "09:30 AM",
  value1000Am: "10:00 AM",
  value1030Am: "10:30 AM",
  value1100Am: "11:00 AM",
  value1130Am: "11:30 AM",
  patientDetails: "Patient Details",
  personIcon: "👤",
  srikanthReddy: "Srikanth Reddy",
  proceedToPay: "Proceed to Pay ",
  value800: "₹800 →",
  bookService: "Book Service",
  anIndividualCustomerMembershipIsRequiredToBookThis:
    "An individual customer membership is required to book this service.",
  contactOhoCare: "Contact OHO Care",
  selectAHospitalForYourZeroCashOpdConsultation:
    "Select a hospital for your Zero-Cash OPD consultation.",
  chooseHospital: "Choose hospital",
  hospitalOrCustomerDetailsCouldNotBeFound:
    "Hospital or customer details could not be found.",
  unableToLoadBookingDetails: "Unable to load booking details.",
  loadingHospitalServicesAndMembership:
    "Loading hospital services and membership...",
  freeConsultation: "Free Consultation",
  comma: ",",
  zeroCashOpd: "Zero-Cash OPD",
  useAnAvailableFreeConsultationCouponForYourselfOr:
    "Use an available free-consultation coupon for yourself or an eligible family member.",
  anActiveUnexpiredMembershipCardIsRequiredToBook:
    "An active, unexpired membership card is required to book this service.",
  viewMembership: "View membership",
  contactSupport: "Contact support",
  freeConsultationIsNotAvailableAtThisHospital:
    "Free consultation is not available at this hospital.",
  chooseAnotherHospital: "Choose another hospital",
  couponAvailabilityCouldNotBeConfirmed:
    "Coupon availability could not be confirmed.",
  unableToCheckCoupons: "Unable to check coupons.",
  selectAFutureAppointmentDateAndTime:
    "Select a future appointment date and time.",
  pleaseSelectAServiceType: "Please select a service type.",
  unableToInitiateTheBooking: "Unable to initiate the booking.",
  unableToBookPleaseTryAgain: "Unable to book. Please try again.",
  selectPatient: "Select patient",
  checkingFreeConsultationCoupons: "Checking free consultation coupons...",
  noCouponsAvailableForThisPatient: "No coupons available for this patient.",
  checkAgain: "Check again",
  appointmentDateTime: "Appointment Date & Time *",
  reasonToVisit: "Reason to Visit",
  enterReasonToVisit: "Enter reason to visit",
  serviceType: "Service Type *",
  selectService: "Select Service",
  noServiceTypesAreCurrentlyAvailablePleaseContactSupport:
    "No service types are currently available. Please contact support.",
  initiatingBooking: "Initiating booking...",
  bookFreeConsultation: "Book Free Consultation",
  yourBookingWillBeInitiatedForTheHospitalTo:
    "Your booking will be initiated for the hospital to confirm. Your coupon is claimed when the visit is completed.",
  viewMyBookings: "View my bookings",
  orderTracking: "Order Tracking",
  orderPlaced: "Order Placed",
  value20May20261000Am: "20 May 2026, 10:00 AM",
  confirmed: "Confirmed",
  value20May20261005Am: "20 May 2026, 10:05 AM",
  packed: "Packed",
  value20May20261130Am: "20 May 2026, 11:30 AM",
  outForDelivery: "Out for Delivery",
  value20May20260400Pm: "20 May 2026, 04:00 PM",
  delivered: "Delivered",
  value20May20260615Pm: "20 May 2026, 06:15 PM",
  checkmark: "✓",
  payment: "Payment",
  amountToPay: "Amount to Pay",
  value8002: "₹800",
  paymentMethods: "Payment Methods",
  upiPhonepeGpayPaytm: "UPI (PhonePe / GPay / Paytm)",
  creditDebitCard: "Credit / Debit Card",
  netBanking: "Net Banking",
  ohoWalletBalance2450: "OHO Wallet · Balance ₹2,450",
  selectedCircleIcon: "◉",
  pay800: "Pay ₹800",
  myBookings: "My Bookings",
  upcoming: "Upcoming",
  completed: "Completed",
  cancelled: "Cancelled",
  doctorProfile: "Doctor Profile",
  heartPrefix: "♡ ",
  experience: " Experience",
  locationPrefix: "⌖ ",
  starPrefix: "★ ",
  reviews: " Reviews)",
  about: "About",
  experience2: "Experience",
  reviews2: "Reviews",
  fees: "Fees",
  cardiologistWith15YearsOfExperienceInInterventionalCardiology:
    "Cardiologist with 15+ years of experience in interventional cardiology, angioplasty, heart failure and preventive cardiology.",
  consultationFee: "Consultation Fee",
  currencySymbol: "₹",
  doctors: "Doctors",
  searchDoctorsOrSpecialty: "Search doctors or specialty...",
  all: "All",
  cardiology: "Cardiology",
  pediatrics: "Pediatrics",
  separator: " · ",
  viewProfile: "View Profile",
  yourBrowserDoesNotSupportLocationYouCanStill:
    "Your browser does not support location. You can still search all hospitals.",
  locationAccessWasDeniedAllowItInYourBrowser:
    "Location access was denied. Allow it in your browser to see distances and nearby hospitals.",
  unableToFindYourLocationPleaseTryAgainAll:
    "Unable to find your location. Please try again; all hospitals remain available.",
  bookServiceChooseHospital: "Book Service · Choose Hospital",
  hospitals: "Hospitals",
  hospitalView: "Hospital view",
  listView: "☷ List view",
  mapView: "⌖ Map view",
  searchHospitals: "Search hospitals",
  searchHospitalsCityOrSpeciality: "Search hospitals, city or speciality...",
  speciality: "Speciality",
  allSpecialities: "All specialities",
  locating: "Locating...",
  updateMyLocation: "Update my location",
  useMyLocation: "Use my location",
  hospitalDistanceFilter: "Hospital distance filter",
  allHospitals: "All hospitals",
  nearest2: "Nearest 2",
  nearby10Km: "Nearby · 10 km",
  loadingHospitals: "Loading hospitals...",
  hospital: " hospital",
  found: " found",
  sortedByDistance: " · Sorted by distance",
  medicalCrossIcon: "✚",
  addressNotProvided: "Address not provided",
  kmAway: " km away",
  details: "Details",
  map: "Map",
  directions: "Directions ↗",
  call2: "Call",
  noHospitalsFound: "No hospitals found",
  tryADifferentSearchSpecialityOrDistanceFilter:
    "Try a different search, speciality or distance filter.",
  clearFilters: "Clear filters",
  copyAHrefHttpsWwwOpenstreetmapOrgCopyrightOpenstreetmap:
    '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
  theMapBackgroundCouldNotLoadYouCanStill:
    "The map background could not load. You can still select hospital pins or use List view.",
  hospital2: "Hospital",
  viewDetails2: "View details",
  getDirections: "Get directions ↗",
  spanAriaHiddenTrueSpan: '<span aria-hidden="true">+</span>',
  yourLocation: "Your location",
  unableToLoadTheInteractiveMapPleaseUseList:
    "Unable to load the interactive map. Please use List view or try again.",
  interactiveHospitalMap: "Interactive hospital map",
  noHospitalsWithValidMapLocationsMatchYourFilters:
    "No hospitals with valid map locations match your filters.",
  hospitalSHaveNoMapLocationFindThemIn:
    " hospital(s) have no map location. Find them in List view.",
  labTests: "Lab Tests",
  searchTests: "Search tests...",
  popular: "Popular",
  bloodTests: "Blood Tests",
  diabetes: "Diabetes",
  thyroid: "Thyroid",
  book: "Book",
  deliveryVanIcon: "🚐",
  bookHomeCollection: "Book Home Collection",
  freeSamplePickupAtYourHome: "Free sample pickup at your home",
  wellnessPackages: "Wellness Packages",
  searchPackages: "Search packages...",
  fullBodyCheckup: "Full Body Checkup",
  seniorCitizen: "Senior Citizen",
  tests: " Tests",
  off: " OFF",
  uploadPrescription: "Upload Prescription",
  getMedicinesAtBestPrices: "Get medicines at best prices",
  uploadNow: "Upload Now",
  decoration1F4C4: "📄",
  allMedicines: "All Medicines",
  healthCare: "Health Care",
  babyCare: "Baby Care",
  devices: "Devices",
  medicineEmoji: "💊",
  bottleEmoji: "🧴",
  babyEmoji: "👶",
  watchEmoji: "⌚",
  orderAgain: "Order Again",
  viewAll: "View All",
  searchHospitals2: "Search hospitals...",
  multiSpeciality: "Multi Speciality",
  cardiac: "Cardiac",
  ortho: "Ortho",
  searchMedicines: "Search medicines...",
  add: "Add",
  hospitalEmoji: "🏥",
  doctorEmoji: "👨🏻‍⚕️",
  labEmoji: "🧪",
  wellness: "Wellness",
  stethoscopeEmoji: "🩺",
  healthCheckups: "Health Checkups",
  packageEmoji: "📦",
  packages: "Packages",
  moreIcon: "•••",
  more: "More",
  noUpcomingAppointments: "No upcoming appointments",
  loadingAppointment: "Loading appointment...",
  appointmentsUnavailable: "Appointments unavailable",
  completeYourDateOfBirthAgeAndGenderIn:
    "Complete your date of birth, age and gender in Profile.",
  addYourAddressInProfile: "Add your address in Profile.",
  kycVerificationUnavailable: "KYC verification unavailable.",
  kycIncompleteCompleteAadhaarPanAndFaceVerificationIn:
    "KYC incomplete: complete Aadhaar, PAN and face verification in Profile.",
  contactSupportForActivation: "Contact support for activation.",
  reviewRenewalOptionsInPackages: "Review renewal options in Packages.",
  yourPackage: "Your package",
  freePackage: "Free package",
  hospitalAppointment: "Hospital appointment",
  booked: "Booked",
  emptyValue: "—",
  guest: "Guest",
  viewProfile2: "View profile",
  hello: "Hello, ",
  decoration1F44B: " 👋",
  familyHealthAccountVault: "Family Health Account Vault",
  liquidity: "Health benefits",
  packageRequired: "Package required",
  activateHealthBenefits: "Activate your health benefits",
  healthBenefitValue: "Health benefit value",
  activeHealthBenefitsDescription:
    "Use eligible healthcare services included in your active package.",
  purchaseHealthBenefitsDescription:
    "Purchase a package to unlock your family healthcare benefits.",
  choosePackage: "Choose a package",
  vaultBenefitOpd: "Zero-Cash OPD consultations",
  vaultBenefitPharmacy: "Pharmacy subsidies",
  vaultBenefitCheckups: "Health checkups",
  vaultPackageBenefitsNote:
    "Included services and limits depend on the package you choose.",
  value37000: "₹ 37,000",
  preLoadedHealthLiquidity: "Pre-loaded Health Liquidity",
  quickServices: "Quick Services",
  upcomingAppointment: "Upcoming Appointment",
  availableFreePackages: "Available free packages",
  todaySHealthTip: "Today's Health Tip",
  healthTipsCurrentlyUnavailable: "Health tips currently unavailable.",
  loadingHealthTips: "Loading health tips...",
  support: "Support:",
  giftEmoji: "🎁",
  needsYourAttention: "Needs your attention",
  dismissNotices: "Dismiss notices",
  dismissIcon: "×",
  reviewProfile: "Review profile",
  viewPackages: "View packages",
  loadingDetails: "Loading details...",
  myMembership: "My Membership",
  healthProducts: "Health Products",
  hospitalNetwork: "Hospital Network",
  myProfile: "My Profile",
  familyMembers2: "Family Members",
  nomineeDetails: "Nominee Details",
  kycVerification2: "KYC Verification",
  accountManagement: "Account Management",
  bmiCalculator: "BMI Calculator",
  meditationBreathing: "Meditation & Breathing",
  stepTracker: "Step Tracker",
  nutritionTracking: "Nutrition Tracking",
  support2: "Support",
  aboutUs: "About Us",
  moreServices: "More Services",
  customerServices: "Customer services",
  customerProfileDetailsAreAvailableForIndividualMemberships:
    "Customer profile details are available for individual memberships.",
  name: "Name",
  addressLine2: "Address line 2",
  village: "Village",
  city: "City",
  pincode: "Pincode",
  viewKycStatus: "View KYC status",
  noIndividualCustomerMembershipIsLinkedToThisAccount:
    "No individual customer membership is linked to this account.",
  relationship: "Relationship",
  noFamilyMembersHaveBeenAdded: "No family members have been added.",
  viewAccountDetails: "View account details",
  bookingDetails: "Booking details",
  yourCareInOnePlace: "YOUR CARE, IN ONE PLACE",
  everyVisit: "Every visit.",
  alwaysWithinReach: "Always within reach.",
  keepTrackOfYourCareAndYourFamilyS:
    "Keep track of your care and your family's appointments.",
  findAHospital: "Find a hospital ",
  filterBookings: "Filter bookings",
  previous: "Previous",
  running: "Running",
  allAppointments: "All appointments",
  bookingUnavailable: "Booking unavailable",
  aLittleRoomForYourNextVisit: "A little room for your next visit",
  thisConsultationWasNotFoundInYourAccount:
    "This consultation was not found in your account.",
  noBookingsFound: "No bookings found.",
  exploreHospitals: "Explore hospitals ",
  forwardArrow: "→",
  hospitalConsultation: "Hospital consultation",
  dateNotScheduled: "Date not scheduled",
  pending: "Pending",
  appointmentDateToBeConfirmed: "Appointment date to be confirmed",
  patientNotProvided: "Patient not provided",
  booking: "BOOKING #",
  statusNotProvided: "Status not provided",
  viewDetails3: "View details ",
  bookedOn: "Booked on",
  appointmentDate: "Appointment date",
  service: "Service",
  patient: "Patient",
  policyDetails: "Policy Details",
  coiNumber: "COI number",
  insuredMembers: "Insured members",
  dependents: "Dependents",
  viewNominees: "View nominees",
  thisPolicyWasNotFoundInYourMembership:
    "This policy was not found in your membership.",
  noNomineesHaveBeenAddedToYourPolicies:
    "No nominees have been added to your policies.",
  paidAmount: "Paid amount",
  viewPolicy: "View policy",
  chevronRightSuffix: " ›",
  noPurchasedPackagesFound: "No purchased packages found.",
  hospitalDetails: "Hospital Details",
  selectAHospitalToViewItsDetails: "Select a hospital to view its details.",
  findAHospital2: "Find a hospital",
  specialization: "Specialization",
  hospitalCode: "Hospital code",
  callHospital: "Call hospital",
  viewOnMap: "View on map",
  servicesBenefits: "Services & Benefits",
  hospitalBenefit: "Hospital benefit",
  discount: "Discount: ",
  percentSymbol: "%",
  noServicesListedForThisHospital: "No services listed for this hospital.",
  bookAnAppointment: "Book an appointment",
  hospitalNotFound: "Hospital not found.",
  productDetails: "Product Details",
  selectAPackageToViewItsDetails: "Select a package to view its details.",
  browseProducts: "Browse products",
  price: "Price",
  adultsCovered: "Adults covered",
  childrenCovered: "Children covered",
  productNotFound: "Product not found.",
  noProductsAvailable: "No products available.",
  kycStatusIsAvailableForIndividualCustomerMemberships:
    "KYC status is available for individual customer memberships.",
  verificationStatusUnavailable: "Verification status unavailable.",
  checkTheVerificationStatusLinkedToYourMembership:
    "Check the verification status linked to your membership.",
  checking: "Checking...",
  checkVerificationStatus: "Check verification status",
  contactSupportForVerificationAssistance:
    "Contact support for verification assistance",
  noMobileNumberIsLinkedToThisAccount:
    "No mobile number is linked to this account.",
  unableToSendOtp: "Unable to send OTP.",
  unableToResetPassword: "Unable to reset password.",
  viewPersonalDetails: "View personal details",
  resetYourFourDigitPasswordUsingAnOtpSent:
    "Reset your four-digit password using an OTP sent to your registered mobile number.",
  sendingOtp: "Sending OTP...",
  resetPassword: "Reset password",
  helpSupport: "Help & Support",
  contactOhoCareForHelpWithMembershipBookingsOr:
    "Contact OHO Care for help with membership, bookings or verification.",
  callOhoCare: "Call OHO Care: ",
  supportContactIsCurrentlyUnavailable:
    "Support contact is currently unavailable.",
  privacyPolicyTerms: "Privacy Policy & Terms",
  readOhoindiaSPrivacyPolicyAndTermsOfService:
    "Read OHOINDIA’s privacy policy and terms of service.",
  readPrivacyPolicy: "Read Privacy Policy ↗",
  readTermsConditions: "Read Terms & Conditions ↗",
  accessYourFamilySHealthBenefitsMembershipsAndHospital:
    "Access your family’s health benefits, memberships and hospital network with OHOINDIA.",
  theServiceReturnedAnUnexpectedResponse:
    "The service returned an unexpected response.",
  unableToLoadDetails: "Unable to load details.",
  heightCm: "Height (cm)",
  weightKg: "Weight (kg)",
  calculateBmi: "Calculate BMI",
  yourBmi: "Your BMI: ",
  breatheIn: "Breathe in",
  hold: "Hold",
  breatheOut: "Breathe out",
  followTheBreathingTimerAtAComfortablePace:
    "Follow the breathing timer at a comfortable pace.",
  readyWhenYouAre: "Ready when you are",
  colon: ":",
  pause: "Pause",
  start: "Start",
  reset: "Reset",
  unableToSaveOnThisDeviceCheckYourBrowser:
    "Unable to save on this device. Check your browser storage settings.",
  walk: "Walk",
  recordTodayS: "Record today’s ",
  entriesAreSavedOnThisDevice: ". Entries are saved on this device.",
  activityOptional: "Activity (optional)",
  meal: "Meal",
  steps: "Steps",
  caloriesKcal: "Calories (kcal)",
  add2: "Add ",
  remove2: "Remove",
  oho: "OHO",
  gold: "GOLD",
  ohoGoldWellnessCard: "OHO Gold Wellness Card",
  cardNo280400015854: "Card No: 2804 0001 5854",
  validTill20Dec2026: "Valid till 20-Dec-2026",
  membershipBenefits: "Membership Benefits",
  discountsAtPartnerHospitals: "Discounts at partner hospitals",
  freeAnnualHealthCheck: "Free annual health check",
  priorityAppointmentBooking: "Priority appointment booking",
  ohoCoinsOnEveryPurchase: "OHO Coins on every purchase",
  checkmarkPrefix: "✓ ",
  today: "Today",
  calendarEmoji: "📅",
  appointmentConfirmed: "Appointment Confirmed",
  drRajeshSharmaOn20May1030Am: "Dr. Rajesh Sharma on 20 May, 10:30 AM",
  labTestReminder: "Lab Test Reminder",
  yourBloodTestIsScheduledTomorrow: "Your blood test is scheduled tomorrow",
  value405m: "4:05m",
  yesterday: "Yesterday",
  offerForYou: "Offer for You",
  get20OffOnHealthPackages: "Get 20% off on health packages",
  mobileNumberNotProvided: "Mobile number not provided",
  myFamily: "My Family",
  manageFamilyMembers: "Manage family members",
  recordsEmoji: "📋",
  myHealthRecords: "My Health Records",
  viewReportsPrescriptions: "View reports & prescriptions",
  medalEmoji: "🏅",
  goldWellnessCard: "Gold Wellness Card",
  purseEmoji: "👛",
  walletRewards: "Wallet & Rewards",
  cashbackOffersCoupons: "Cashback, offers & coupons",
  paymentCardEmoji: "💳",
  cardsUpiWallets: "Cards, UPI & wallets",
  supportEmoji: "🎧",
  helpSupport2: "Help & support",
  membershipKycHospitalNetworkWellness:
    "Membership, KYC, hospital network & wellness",
  logoutIcon: "↪",
  logout: "Logout",
  signOutOfYourAccount: "Sign out of your account",
  familyDetails: "Family details",
  healthRecords: "Health Records",
  reports: "Reports",
  prescriptions: "Prescriptions",
  bloodTestReport: "Blood Test Report",
  value20May2026: "20 May 2026",
  xRayChest: "X-Ray Chest",
  value15Apr2026: "15 Apr 2026",
  ecgReport: "ECG Report",
  value10Mar2026: "10 Mar 2026",
  mriScan: "MRI Scan",
  value05Feb2026: "05 Feb 2026",
  totalBalance: "Total Balance",
  value2450: "₹2,450",
  cashback: "Cashback",
  value850: "₹850",
  ohoCoins: "OHO Coins",
  value1600: "🪙 1,600",
  transferIcon: "↔",
  transactionHistory: "Transaction History",
  viewRecentTransactions: "View recent transactions",
  redeemCoins: "Redeem Coins",
  useCoinsForRewards: "Use coins for rewards",
  sr: "SR",
  self: "Self",
  manEmoji: "👨🏻",
  sujathaReddy: "Sujatha Reddy",
  wife: "Wife",
  womanEmoji: "👩🏻",
  chinnuReddy: "Chinnu Reddy",
  daughter: "Daughter",
  girlEmoji: "👧🏻",
  addFamilyMember: "+ Add Family Member",
  noCard: "No card",
  loadingMembership: "Loading membership...",
  noMembershipCard: "No membership card",
  membershipUnavailable: "Membership unavailable",
  ohoMembershipCard: "OHO Membership Card",
} as const;

// Resolve at access time so shared utilities use the same language as screens.
export const UI_TEXT = new Proxy(ENGLISH_TEXT, {
  get(target, key: keyof typeof ENGLISH_TEXT) {
    return translate(target[key]);
  },
}) as { [K in keyof typeof ENGLISH_TEXT]: string };

// Formatting functions keep dynamic display messages consistent across platforms.
export const UI_MESSAGES = {
  ageInYears: (age: string | number) => formatMessage("{0} years", [age]),
  relationshipSuffix: (relationship: string) =>
    formatMessage(" ({0})", [relationship]),
  appointmentPeriod: (period: string) =>
    formatMessage("{0} appointments", [period]),
  adultCount: (count: number) => formatMessage("{0} adults", [count]),
  childCount: (count: number) => formatMessage("{0} children", [count]),
  ohoindiaCustomerApp: (customerName: string) =>
    formatMessage("{0} | OHOINDIA CUSTOMER APP", [customerName]),
  enterThe6DigitOtpSentTo91: (phonePrefix: string, phoneSuffix: string) =>
    formatMessage("Enter the 6-digit OTP sent to +91 {0} {1}.", [
      phonePrefix,
      phoneSuffix,
    ]),
  resendOtpInS: (seconds: number) =>
    formatMessage("Resend OTP in {0}s", [seconds]),
  freeConsultationCouponAvailable: (count: number, pluralSuffix: string) =>
    formatMessage("{0} free consultation coupon{1} available", [
      count,
      pluralSuffix,
    ]),
  showOnMap: (hospitalName: unknown) =>
    formatMessage("Show {0} on map", [hospitalName]),
  yourMembershipCardIs: (status: string, action: string) =>
    formatMessage("Your membership card is {0}. {1}", [status, action]),
  reviewRenewalOptionsInPackages2: (packageName: string, status: string) =>
    formatMessage("{0}: {1}. Review renewal options in Packages.", [
      packageName,
      status,
    ]),
  membership2: (status: string) => formatMessage("Membership {0}", [status]),
  noBookingsFound2: (period: string) =>
    formatMessage("No {0} bookings found.", [period]),
  aadhaarPan: (aadhaarStatus: string, panStatus: string) =>
    formatMessage("Aadhaar: {0}. PAN: {1}.", [aadhaarStatus, panStatus]),
  remove: (label: string) => formatMessage("Remove {0}", [label]),
};
