version = 0.1

[default.deploy.parameters]
stack_name = "oho-customer-api-dev"
resolve_s3 = true
s3_prefix = "oho-customer-api-dev"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "VpcSubnetIds=\"\" VpcSecurityGroupIds=\"\" OnboardingSmsQueueArn=\"\" AllowedFrontendOrigins=\"http://localhost:5173,https://develop.d1fysopts5fr14.amplifyapp.com\" ApiReservedConcurrency=\"20\""
image_repositories = []

[default.global.parameters]
region = "ap-south-1"
